# Generated by Django 4.1.2 on 2023-02-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
