# Generated by Django 4.1.2 on 2023-02-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_updated_at_fooditem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
